# Generated by Django 5.1.6 on 2025-02-12 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0005_auto_20220903_1806"),
    ]

    operations = [
        migrations.CreateModel(
            name="CannedHint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.FloatField(
                        help_text="Order in the puzzle - use 0 for a hint at the very beginning of the puzzle, or 100 for a hint on extraction, and then do your best to extrapolate in between. Decimals are okay. For multiple subpuzzles, assign a whole number to each subpuzzle and use decimals off of that whole number for multiple hints in the subpuzzle."
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="A description of when this hint should apply",
                        max_length=1000,
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated keywords to look for in hunters' hint requests before displaying this hint suggestion",
                        max_length=100,
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        help_text="Canned hint to give a team (can be edited by us before giving it)",
                        max_length=1000,
                    ),
                ),
                (
                    "puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canned_hints",
                        to="puzzles.puzzle",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("puzzle", "description")},
            },
        ),
    ]
