# Generated by Django 5.1.6 on 2025-02-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0006_cannedhint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="erratum",
            name="published",
            field=models.BooleanField(
                default=False,
                help_text="\n        Is this erratum visible to solvers? If the erratum is created with this field\n        checked, it will send emails to all solvers on teams who have unlocked, but not\n        solved, the puzzle. Emails are also sent when the erratum is edited to change\n        this field from unchecked to checked.\n        ",
                verbose_name="Published",
            ),
        ),
    ]
