# Generated by Django 5.1.6 on 2025-02-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0007_alter_erratum_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="answersubmission",
            name="is_message",
            field=models.BooleanField(default=False, verbose_name="Is partial message"),
        ),
        migrations.AddField(
            model_name="answersubmission",
            name="response",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="erratum",
            name="published",
            field=models.BooleanField(
                default=False,
                help_text="\n        Is this erratum visible to solvers? If the erratum is created with this\n        field checked, it will send emails to all solvers on teams who have unlocked,\n        but not solved, the puzzle.\n\n        The email will _not_ send if you are changing/updating an erratum!\n        ",
                verbose_name="Published",
            ),
        ),
    ]
