# Generated by Django 5.1.6 on 2025-02-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0008_answersubmission_is_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HintClaimer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discord_user_id",
                    models.CharField(max_length=255, verbose_name="Discord user id"),
                ),
                (
                    "username",
                    models.CharField(max_length=255, verbose_name="Discord user id"),
                ),
                (
                    "display_name",
                    models.CharField(
                        max_length=255, verbose_name="Discord display name"
                    ),
                ),
                (
                    "avatar_url",
                    models.CharField(max_length=255, verbose_name="Discord avatar URL"),
                ),
            ],
        ),
    ]
