# Generated by Django 5.1.6 on 2025-02-25 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0009_hintclaimer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hint",
            name="claimer",
        ),
        migrations.AddField(
            model_name="hint",
            name="claimed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="puzzles.hintclaimer",
                verbose_name="claimed_by",
            ),
        ),
        migrations.AlterField(
            model_name="hintclaimer",
            name="username",
            field=models.CharField(max_length=255, verbose_name="Discord username"),
        ),
    ]
