# Generated by Django 5.1.6 on 2025-03-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0010_remove_hint_claimer_hint_claimed_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="max_guesses",
            field=models.IntegerField(
                default=None,
                help_text="Override number of max guesses",
                null=True,
                verbose_name="Max guesses",
            ),
        ),
    ]
