# Generated by Django 5.1.6 on 2025-03-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0011_puzzle_max_guesses"),
    ]

    operations = [
        migrations.AddField(
            model_name="erratum",
            name="is_announcement",
            field=models.BooleanField(
                default=False,
                help_text='\n        Is this an announcement? If this is created with this field checked,\n        it will not appear on the /updates page. It will also use a different template,\n        ignore the selected "puzzle", and send emails to all registered hunters.\n\n        "subject" should be filled, and "published" should be checked if this is an\n        announcement.\n        ',
                verbose_name="Display update?",
            ),
        ),
        migrations.AddField(
            model_name="erratum",
            name="subject",
            field=models.CharField(
                blank=True,
                help_text="Override email subject",
                max_length=255,
                verbose_name="Email subject",
            ),
        ),
    ]
