# Generated by Django 5.1.6 on 2025-03-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0012_erratum_is_announcement_erratum_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="erratum",
            name="is_announcement",
            field=models.BooleanField(
                default=False,
                help_text='\n        Is this an announcement? If this is created with this field checked,\n        it will not appear on the /updates page. It will also use a different template,\n        ignore the selected "puzzle", and send emails to all registered hunters.\n\n        If this is an announcement, "puzzle" should be empty; "subject" should be\n        filled; and "published" should be checked.\n        ',
                verbose_name="Announcement?",
            ),
        ),
        migrations.AlterField(
            model_name="erratum",
            name="updates_text",
            field=models.TextField(
                blank=True,
                help_text='\n        Text to show on the Updates (errata) page, and which will be emailed to teams.\n        If blank, it will not appear there.\n        Use $PUZZLE to refer to the puzzle. The text will be prefixed with "On\n        (date)," when displayed, so you should capitalize it the way it would\n        appear mid-sentence. HTML is ok.\n    ',
                verbose_name="Updates text",
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="max_guesses",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Override number of max guesses",
                null=True,
                verbose_name="Max guesses",
            ),
        ),
    ]
